name: Deploy to All Store for Production
on:
  workflow_dispatch:
    inputs:
      version:
        description: App version to be deploy
        required: false

jobs:
  fastlane-android-deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Play Store Production
    runs-on: ubuntu-latest
    steps:
      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter doctor -v

      # Checkout 8conlay mobile app code and get packages.
      - name: Checkout 8conlay mobile app code
        uses: actions/checkout@v2
      - run: flutter pub get
      
      - name: Set App version number
        if: ${{ github.event.inputs.version != '' }}       
        run: |
          sed -i "s/^version:.*/version: ${{ github.event.inputs.version }}/g" pubspec.yaml

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      # Naturally, promote_to_production only deploys.
      - run: bundle exec fastlane release_production_ci
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      - uses: EndBug/add-and-commit@v7
        with:
          message: Update the repo after the build complete
