name: Deploy to All Store for Production
on:
  workflow_dispatch:
    inputs:
      version:
        description: App version to be deploy
        required: false

jobs:
  fastlane-ios-deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to App Store Production
    runs-on: macos-latest
      
    steps:
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter doctor -v

    # Checkout 8conlay mobile app code and get packages.
      - name: Checkout 8conlay mobile app code
        uses: actions/checkout@v2
      - run: flutter pub get

      - name: Set App version number
        if: ${{ github.event.inputs.version != '' }}       
        run: |
          sed -i "s/^version:.*/version: ${{ github.event.inputs.version }}/g" pubspec.yaml
    
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: ios
        
      - name: Install Pods
        run: pod install
        working-directory: ios
            
      - name: Build & Distribute to Testflight 
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          bundle exec fastlane release_production
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          MATCH_DEPLOY_KEY: "${{ secrets.SSH_KEY }}"
          MATCH_KEYCHAIN_NAME: "${{ secrets.MATCH_KEYCHAIN_NAME }}"
          MATCH_KEYCHAIN_PASSWORD: "${{ secrets.MATCH_KEYCHAIN_PASSWORD }}"
        working-directory: ios

  fastlane-huawei-deploy-prod:
    name: Deploy to App Gallery Production
    runs-on: ubuntu-latest
    steps:
      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter doctor -v

      # Checkout 8conlay mobile app code and get packages.
      - name: Checkout 8conlay mobile app code
        uses: actions/checkout@v2
      - run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      # Build and deploy with Fastlane (by default, to beta track) 🚀.
      # Naturally, promote_to_production only deploys.
      - run: bundle exec fastlane huawei_production
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      - uses: EndBug/add-and-commit@v7
        with:
          message: Update the repo after the build complete
