name: Deploy to Play Store for QA
on:
  workflow_dispatch:
    inputs:
      version:
        description: App version to be deploy
        required: false

jobs:
  fastlane-ios-deploy-qa:
    name: Deploy to App Store Testflight QA
    runs-on: macos-latest
    steps:

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter doctor -v

    # Checkout 8conlay mobile app code and get packages.
      - name: Checkout 8conlay mobile app code
        uses: actions/checkout@v2
      - run: flutter pub get

      - name: Set App version number
        if: ${{ github.event.inputs.version != '' }}       
        run: |
          sed -i "s/^version:.*/version: ${{ github.event.inputs.version }}/g" pubspec.yaml
    
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: ios
        
      - name: Install Pods
        run: pod install
        working-directory: ios
            
      - name: Build & Distribute to Testflight 
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          bundle exec fastlane test_qa
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          MATCH_DEPLOY_KEY: "${{ secrets.SSH_KEY }}"
          MATCH_KEYCHAIN_NAME: "${{ secrets.MATCH_KEYCHAIN_NAME }}"
          MATCH_KEYCHAIN_PASSWORD: "${{ secrets.MATCH_KEYCHAIN_PASSWORD }}"
        working-directory: ios

      - uses: EndBug/add-and-commit@v7
        with:
          message: Update the repo after the build complete

