name: Test Github API

on:
  workflow_dispatch:

jobs:
      
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - run: echo ${{ github.ref }} "test workflow"
